services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    env_file:
      - .env.build
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD-hashPasWord1}
    ports:
      - "9200:9200"
    networks:
      - app-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.14.3
    ports:
      - '5601:5601'
    depends_on:
      - elastic-search
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: '["http://elastic-search:9200"]'
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3000"
    depends_on:
      - db-test
      - elastic-search
    networks:
      - app-network

  db-test:
    image: mysql:9.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD-HashPassw0rd1}
    ports:
      - "3308:3306"
    networks:
      - app-network
    volumes:
      - dbdata:/var/lib/mysql
      - ./initial-data.sql:/docker-entrypoint-initdb.d/init-db.sql

networks:
  app-network:

volumes:
  certs:
    driver: local
  kibanadata:
    driver: local
  dbdata:
    driver: local
